### PR TITLE
fix(STONEINTG-434): allow for snapshots without valid component defined in label

### PR DESCRIPTION
**Pull request by hongweiliu17**
Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Comment by hongweiliu17** [comment]
Look at GetComponentFromSnapshot() called in [snapshot_controller.go](https://github.com/redhat-appstudio/integration-service/blob/9ae5f506922ba9a1a9f47b0edb135b3bbc6b8b53/controllers/snapshot/snapshot_controller.go#L86-L90)
```
func GetComponentFromSnapshot(c client.Client, ctx context.Context, snapshot *applicationapiv1alpha1.Snapshot) (*applicationapiv1alpha1.Component, error) {
    if componentLabel, ok := snapshot.Labels[gitops.SnapshotComponentLabel]; ok {
        component := &applicationapiv1alpha1.Component{}
        err := c.Get(ctx, types.NamespacedName{
            Namespace: snapshot.Namespace,
            Name:      componentLabel,
        }, component)        
        if err != nil {
            return nil, err
        }
        return component, nil
    } else {
        return nil, nil
    }
}
```

If label `Labels[gitops.SnapshotComponentLabel]` exists but that component doesn't exist at all in cluster,  `nil, err` will be returned to [snapshot_controller.go](https://github.com/redhat-appstudio/integration-service/blob/9ae5f506922ba9a1a9f47b0edb135b3bbc6b8b53/controllers/snapshot/snapshot_controller.go#L86-L90), we will log error `Failed to get Component from the Snapshot` in [code](https://github.com/redhat-appstudio/integration-service/blob/9ae5f506922ba9a1a9f47b0edb135b3bbc6b8b53/controllers/snapshot/snapshot_controller.go#L88),  pr https://github.com/redhat-appstudio/integration-service/pull/202 is committed to allow this nonexisting component. But is  this a valid scenario that component defined in label `Labels[gitops.SnapshotComponentLabel]` doesn't exist? @dirgim 

If label `Labels[gitops.SnapshotComponentLabel]` doesn't exist, `nil, nil` will be returned to [snapshot_controller.go](https://github.com/redhat-appstudio/integration-service/blob/9ae5f506922ba9a1a9f47b0edb135b3bbc6b8b53/controllers/snapshot/snapshot_controller.go#L86-L90), I this this is an expected result, for composite snapshot.

**Comment by hongweiliu17** [comment]
Hi @dirgim , second question. If no valid component defined in snapshot label `Labels[gitops.SnapshotComponentLabel]`, we can always get component in [snapshot_adapter.go function GetAllApplicationComponents()](https://github.com/redhat-appstudio/integration-service/blob/main/controllers/snapshot/snapshot_adapter.go#L213) for this snapshot when creating binding, right?  I am confused. Thank you!

**Comment by dirgim** [comment]
@hongweiliu17 you are correct,  if the label is present on the Snapshot, the component should exist. 
The Integration service already acts correctly by reporting an error if the label is there and the component doesn't exist, so this bugfix is not needed.
The SnapshotEnvironmentBinding can always be created because it does not depend on the component label.
Thank you for analyzing the issue and raising the questions.

**Comment by hongweiliu17** [comment]
> 

Thank you Kruno! Let me close this PR.

**Pull request closed without merging**
