### PR TITLE
feat(HACBS-1592): don't merge, it is a test

### PR DESCRIPTION
**Pull request by jinqi7**

### CODE REVIEW

**Comment by dirgim** [comment]
This is looking great, nice work @jinqi7! Do we need to use tide or can we ignore it and keep merging PRs as normal?

**Comment by jinqi7** [comment]
> This is looking great, nice work @jinqi7! Do we need to use tide or can we ignore it and keep merging PRs as normal?

Most of other repos in redhat-appstudio used tide.  Can we keep it and just add /lgtm label to make PRs merged?@dirgim

**Comment by dirgim** [comment]
> > This is looking great, nice work @jinqi7! Do we need to use tide or can we ignore it and keep merging PRs as normal?
> 
> Most of other repos in redhat-appstudio used tide. Can we keep it and just add /lgtm label to make PRs merged?@dirgim

The issue with using tide is that it is in charge of requirements for merging PRs - it removes the requirements for our existing CI tests and it automatically merges after just single approval, which is not in line with our requirements.

**Comment by jinqi7** [comment]
> @jinqi7 are you ok with closing this PR now that the [HACBS-1592](https://issues.redhat.com//browse/HACBS-1592) feature is fully working?
I didn't notice your comment @dirgim . Closed

**Pull request closed without merging**
