### PR TITLE
fix(stoneintg-499):  remove replica configuration from SEB

### PR DESCRIPTION
**Pull request by sonam1412**
Remove the replica configuration from the component.Spec of SnapshotEnvironmentBinding. [See]([RHTAPBUGS-173](https://issues.redhat.com/browse/RHTAPBUGS-173)).

### CODE REVIEW

**Comment by sonam1412** [comment]
[Screenshots](https://issues.redhat.com/browse/STONEINTG-499?focusedId=22575738&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22575738) from the testing on the dev cluster.

**Comment by dirgim** [comment]
Looks like the e2e tests are failing when creating SEBs ([log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_integration-service/239/pull-ci-redhat-appstudio-integration-service-main-integration-service-e2e/1677203914857910272/artifacts/integration-service-e2e/gather-extra/artifacts/pods/integration-service_integration-service-integration-service-controller-managermrn69_manager.log)):
```
Failed to create SnapshotEnvironmentBinding for snapshot","snapshot":"integration-e2e-tenant/snapshot-sample-tfes","application":"integration-e2e-tenant/integ-app-kawk","environment":"development","snapshot":"snapshot-sample-tfes","error":"snapshotenvironmentbindings.appstudio.redhat.com \"integ-app-kawk-development-binding-cxph6\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>",
```
I think that rebasing on the latest `main` should resolve that failure.

**Review by jsztuka — APPROVED** [review]
lgtm

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
