### PR TITLE
fix: don't use exclamation marks in text

### PR DESCRIPTION
**Pull request by MartinBasti**
We should refrains from using exclamation marks in text/logs/messages

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Review by dheerajodha — APPROVED** [review]
lgtm

**Review by dheerajodha — APPROVED** [review]
lgtm

**Review by sonam1412 — APPROVED** [review]
LGTM

**Review by hongweiliu17 — COMMENTED** [review]
Yes, thanks for the PR.

**Pull request merged**
