### PR TITLE
fix(HACBS-1256): add fix to make test error

### PR DESCRIPTION
**Pull request by srivickynesh**
Signed-off-by: Sri Vignesh <sselvan@redhat.com>

### CODE REVIEW

**Comment by dirgim** [comment]
@srivickynesh the fix looks good, but can you modify the commit title to reference the HACBS-1256 ticket?

**Review by dirgim — APPROVED** [review]
LGTM

**Review by jsztuka — APPROVED** [review]
lgtm

**Review by sonam1412 — APPROVED** [review]
LGTM

**Pull request merged**
