### PR TITLE
Fix for the integrationtestscenario_viewer_role yaml file name

### PR DESCRIPTION
**Pull request by hongweiliu17**

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
~LGTM~

**Review by dirgim — CHANGES_REQUESTED** [review]
Looks like we'll need the same fix [here](https://github.com/redhat-appstudio/integration-service/blob/main/config/kcp-rbac/kustomization.yaml#L15)

**Comment by hongweiliu17** [comment]
> 
I am updating https://github.com/redhat-appstudio/integration-service/blob/main/config/kcp-rbac/kustomization.yaml#L15, is it?

**Review by dirgim — APPROVED** [review]
LGTM

**Review by jinqi7 — APPROVED** [review]
LGTM

**Pull request merged**
