### PR TITLE
feat(HACBS-1215): use the Red Hat go 1.18 image in the Integration service

### PR DESCRIPTION
**Pull request by hongweiliu17**
Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Comment by dirgim** [comment]
We'll also need to do the changes in the Dockerfile like in [this commit](https://github.com/redhat-appstudio/integration-service/commit/02f8badbd530f1ee94a0326b56980384cb12e879#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).

**Comment by hongweiliu17** [comment]
> We'll also need to do the changes in the Dockerfile like in [this commit](https://github.com/redhat-appstudio/integration-service/commit/02f8badbd530f1ee94a0326b56980384cb12e879#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).

Thanks so much @dirgim. It works when I use it like this https://github.com/redhat-appstudio/integration-service/pull/78/commits/50189fa4569d3df788b01a5eb7d7227ef54bb8ce! But do you know why it fails when I use them like this https://github.com/redhat-appstudio/integration-service/pull/78/commits/ba67ea92a973f799ea923747bf4c8fbd19a368c2? Thank you!!

**Comment by hongweiliu17** [comment]
> > We'll also need to do the changes in the Dockerfile like in [this commit](https://github.com/redhat-appstudio/integration-service/commit/02f8badbd530f1ee94a0326b56980384cb12e879#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).
> 
> Thanks so much @dirgim. It works when I use it like this [50189fa](https://github.com/redhat-appstudio/integration-service/commit/50189fa4569d3df788b01a5eb7d7227ef54bb8ce)! But do you know why it fails when I use them like this commit [ba67ea9](https://github.com/redhat-appstudio/integration-service/commit/ba67ea92a973f799ea923747bf4c8fbd19a368c2)? Thank you!!

**Comment by hongweiliu17** [comment]
> > > We'll also need to do the changes in the Dockerfile like in [this commit](https://github.com/redhat-appstudio/integration-service/commit/02f8badbd530f1ee94a0326b56980384cb12e879#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).
> > 
> > 
> > Thanks so much @dirgim. It works when I use it like this [50189fa](https://github.com/redhat-appstudio/integration-service/commit/50189fa4569d3df788b01a5eb7d7227ef54bb8ce)! But do you know why it fails when I use them like this commit [ba67ea9](https://github.com/redhat-appstudio/integration-service/commit/ba67ea92a973f799ea923747bf4c8fbd19a368c2)? Thank you!!

I know why now, `/workspace` doesn't exist.

**Review by amisstea — APPROVED** [review]
LGTM :+1:

**Review by dirgim — APPROVED** [review]
LGTM

**Review by sonam1412 — APPROVED** [review]
LGTM

**Pull request merged**
