### PR TITLE
feat(HACBS-1331): remove the test prefix from appstudio resource labels

### PR DESCRIPTION
**Pull request by sonam1412**
Signed-off-by: @sonam1412 somahesh@redhat.com

This is to remove the test prefix from appstudio resource labels

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Review by srivickynesh — APPROVED** [review]
LGTM

**Review by jsztuka — APPROVED** [review]
LGTM

**Review by dirgim — APPROVED** [review]
LGTM, nice catch on the build labels

**Pull request merged**
