### PR TITLE
fix(STONEINTG-519): remove the networkPolicy that prevents egress

### PR DESCRIPTION
**Pull request by sonam1412**
- This PR is created to remove the network policy that prevents egress from the integration-service to be able to access internet(github.com)

- This is required in order to make reporting possible on the GitHub PaC PRs.
- This PR is reverting https://github.com/redhat-appstudio/integration-service/commit/e7667698900041a36142e7c625f0beee4b8dfefc

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by dheerajodha** [comment]
@sonam1412 were you able to do `curl https://github.com/`?

**Comment by sonam1412** [comment]
> @sonam1412 were you able to do `curl https://github.com/`?

I did as you can see [here](https://issues.redhat.com/browse/STONEINTG-519?focusedId=22762558&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22762558)

**Comment by MartinBasti** [comment]
Commit message should contain info why, and would be nice to mention digest of commits we are reverting here
(e7667698900041a36142e7c625f0beee4b8dfefc)

**Comment by sonam1412** [comment]
> Commit message should contain info why, and would be nice to mention digest of commits we are reverting here ([e766769](https://github.com/redhat-appstudio/integration-service/commit/e7667698900041a36142e7c625f0beee4b8dfefc))

ACK

**Comment by dirgim** [comment]
> > Commit message should contain info why, and would be nice to mention digest of commits we are reverting here ([e766769](https://github.com/redhat-appstudio/integration-service/commit/e7667698900041a36142e7c625f0beee4b8dfefc))
> 
> By updating the commit message to add the reason the glint check is failing for the long commit message. Any suggestions to fix that please ?

The CI fails on this:
```
B1 Line exceeds max length (118>72): "This is required in order to be able to access internet(github.com) and make reporting possible on the GitHub PaC PRs."
```
Breaking up that line should resolve the issue.

**Comment by MartinBasti** [comment]
Code looks good, I'm just thinking, because that object already exists in OCP deployments, will argoCD remove it when we removed definition, or do we need extra action to enforce removal?

**Review by dheerajodha — APPROVED** [review]
LGTM

**Review by Josh-Everett — APPROVED** [review]

**Pull request merged**
