### PR TITLE
fix: update a few text/message in build/integration PLR

### PR DESCRIPTION
**Pull request by hongweiliu17**
In STONEINTG-493, we split PLR controller to build PLR controller and integration PLR controller, this PR is to update some text/message which are not updated in https://github.com/redhat-appstudio/integration-service/pull/257 

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

## Maintainers will complete the following section

- [ ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] [Controllers diagrams](https://github.com/redhat-appstudio/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Review by dheerajodha — APPROVED** [review]
Thanks for the PR!
lgtm

**Comment by dheerajodha** [comment]
Can you expand your commit message and mention the same thing you wrote in the PR description? To make the commit message description enough.
```
In STONEINTG-493, we split PLR controller to build PLR controller and integration PLR controller,
this PR is to update some text/message which are not updated in #257
```

**Comment by hongweiliu17** [comment]
> 

Updated. Thanks.

**Review by Josh-Everett — APPROVED** [review]

**Pull request merged**
