### PR TITLE
refactor(STONEINTG-621): move intg. test status code into pkg

### PR DESCRIPTION
**Pull request by MartinBasti**
Moving code for "SnapshotIntegrationTestStatuses" and "IntegrationTestStatusDetail" into separate package to allow import to other projects as library.

Little bit of refactoring done to avoid dependencies on gitopts package.

## Maintainers will complete the following section

- [x] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [x] Code coverage from testing does not decrease and new code is covered
- [x] [Controllers diagrams](https://github.com/redhat-appstudio/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

### CODE REVIEW

**Comment by MartinBasti** [comment]
if you have better naming ideas, feel free to suggest

**Comment by MartinBasti** [comment]
Trying to debug why tests didn't run
```
ok  	github.com/redhat-appstudio/integration-service/pkg/integrationteststatus	0.005s	coverage: 0.0% of statements [no tests to run]

```

And why do I see this in build here, while it works fine on my computer :D
```
#24 [builder 18/18] RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go
111
#24 2.301 gitops/snapshot_integration_tests_status.go:25:2: no required module provides package github.com/redhat-appstudio/integration-service/pkg/integrationteststatus; to add it:
112
#24 2.301 	go get github.com/redhat-appstudio/integration-service/pkg/integrationteststatus
113
#24 ERROR: process "/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go" did not complete successfully: exit code: 1
```

**Comment by dirgim** [comment]
This might need to be done in two PRs - first adding everything under `pkg/` and after that updating the code that uses it in a separate PR.

**Comment by MartinBasti** [comment]
Solved, it was caused by the way how Dockerfile is written

**Review by hongweiliu17 — COMMENTED** [review]
It looks good to me overall.

**Comment by jinqi7** [comment]
LGTM

**Review by jinqi7 — APPROVED** [review]

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
